name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install NPM dependencies
      run: npm install

    - name: Pack the package
      run: npm pack

    # - name: Rename file
    #   run: |
    #     pwd
    #     ls -la
    #     mv sap-openapi-specification-0.14.0.tgz @sap/openapi-specification.tgz

    - name: Upload package to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GH_TOKEN }}
        file: sap-openapi-specification-0.14.0.tgz
        tag: "0.14.0"
        overwrite: true

